project:
  type: website
  output-dir: docs

website:
  title: "Laura Palacios Falk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - SantaCruzPredictions.qmd
  

format:
  html:
    theme: minty
    css: styles.css
    toc: true



